version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - chrome

  chrome:
    image: zenika/alpine-chrome:with-node
    shm_size: 2g
    environment:
      - START_XVFB=true

volumes:
  jenkins_home:
