version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - chrome

  chrome:
    build:
      context: .
      dockerfile: Dockerfile.chrome
    shm_size: 2g
    ports:
      - "9515:9515"
    command: chromedriver --url-base=/ --port=9515 --whitelisted-ips=

volumes:
  jenkins_home: